### ISSUE TITLE
Remove Ruby as a project dependency

### ISSUE THREAD

**Issue by jacekbilski** [project-tenjin/backend#10]
## Motivation
Ruby is currently necessary to run JavaScript tests. [Jasmine](https://jasmine.github.io/index.html), JavaScript testing framework, is using Ruby to start. There are two problems here:
1. Jasmine for Ruby is discontinued and we should not be using it.
2. It's mainly a Java project. On the frontend and for the tests it's using JavaScript. Yet another language is only increasing complexity without adding value.

## Is
Project requires Ruby to be installed.

## Should
Project does not require Ruby to be installed.

## Acceptance Criteria
- All dependencies against Ruby are removed from the project.
- All functionality is kept as-is, i.e. tests or the application itself can be run locally without having Ruby installed.

**Comment by erikpetzold** [comment]
I would suggest to let npm manage installation and execution of jasmine. 

Then I guess there is sth to "embed" npm in gradle. At least for maven there is https://github.com/eirslett/frontend-maven-plugin, I guess sth like this should be possible for gradle too.
So gradle would then trigger download and trigger npm during the build process and npm would take care for jasmine.
