### ISSUE TITLE
Showing a user-friendly error message on the front-end

### ISSUE THREAD

**Issue by project-tenjin** [project-tenjin/backend#12]
## Motivation
We want to show the users an error message so they know what to do or who to contact.

## Is
Error codes are shown (e.g. "404" or "500").

## Should
An error message is shown that lets the user know what to do or who to contact.

## Acceptance Criteria
- If any error occurs, the message should be shown "Oops... That didn't work! Please contact ReDI School (error code: XYZ)"

## Implementation Hints
- the change would be in `src/main/resources/templates/error.html`
- you can also create error pages for specific status codes, for 403 you would get `resources/templates/403.html`
- the "html" is a thymeleaf template: https://www.thymeleaf.org/
- to create an error (for local testing) just throw a new Exception somewhere in the code, for example in `CourseSummaryController.listCourses`

**Comment by Rappahannock** [comment]
#7 #8

**Comment by Rappahannock** [comment]
#8
