### ISSUE TITLE
Not being redirected to 'thanks' from 'attendance' (404: not found)

### ISSUE THREAD

**Issue by project-tenjin** [project-tenjin/backend#8]
![image](https://user-images.githubusercontent.com/20902111/212478871-7edf820a-48c4-4caa-ba8c-aaf2590b6e61.png)
![image](https://user-images.githubusercontent.com/20902111/212478879-dbb2de1d-3b93-4547-a9b1-e0a5376c47bb.png)
[project-tenjin-logs-1673549474615.txt](https://github.com/project-tenjin/backend/files/10405244/project-tenjin-logs-1673549474615.txt)
## environment information

- **Stage**: production

## Description
When we submit attendance we are not redirected to the thanks screen. There is a 404 error in the logs, so it seems the data couldn't be posted.

**Comment by Rappahannock** [comment]
I created a new testing sheet (by copying the original testing sheet and turning on editor rights for everyone with link) and updated the sheet id on PROD to https://docs.google.com/spreadsheets/d/1u_CZFcuNYwWzLeyg3QMkC_tjgdfZRfwOyfUCUAxtOaA and it worked with it!

For the original testing sheet I don't have edit rights (https://docs.google.com/spreadsheets/d/1Jy7VQQFKE7v4sARQyDw5-ulTGlhjts4dmOxG5vGdi4s)

**Comment by erikpetzold** [comment]
This happens when the service account user does not have write permission on the google sheet

TODO add logs and useful error messages

**Comment by project-tenjin** [comment]
We added the service user email to the Google Sheet with Editor rights.
